[package]
name = "MessageBoard"
version = "1.0.0"
authors = []

[addresses]
todolist_addr = "0xc0a22c5608bf0f2ee21fc1732fe8ce0612182ce80bc525aea3e8d3d8548e8ace"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
